### ISSUE TITLE
How can we unit / integration test our extensions?

### ISSUE THREAD

**Issue by danielpacak** [lensapp/lens-extension-samples#15]
I think it would be super nice to see an example of unit test for extension's components with a recommended set of npm dependencies that do not conflict with core extensions API modules.

**Comment by chenhunghan** [comment]
There are some examples in generator template https://github.com/lensapp/generator-lens-ext/tree/main/generators/app/templates/ext-ts/components

**Comment by danielpacak** [comment]
Thanks @chenhunghan I also found the docs explaining how to test https://docs.k8slens.dev/v4.0.6/extensions/testing-and-publishing/testing/
